---

- name: Install fail2ban
  apt: pkg=fail2ban state=installed update_cache=true
  register: fail2ban_installed

- name: Checking if /var/log/nginx/error.log exists
  stat: path=/var/log/nginx/error.log
  register: nginx_log_status

- name: Generate configurations
  template: >
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner=root group=root mode=0600
  with_items:
    - { src: jail.local.j2, dest: /etc/fail2ban/jail.local }
  notify: Restart fail2ban

# - debug: msg="{{ system_packages_installed }}"
